# Generated by Django 2.1 on 2019-09-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=45)),
                ('Contraseña', models.CharField(max_length=45)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Rol')),
            ],
        ),
    ]
