# Generated by Django 2.1 on 2019-09-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='Estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Estado',
            field=models.BooleanField(null=True),
        ),
    ]
