# Generated by Django 2.1 on 2019-09-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20190909_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Identificacion', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Direccion', models.CharField(max_length=45)),
                ('Genero', models.CharField(max_length=45)),
                ('Estado', models.BooleanField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.DateTimeField()),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Estado', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=45)),
                ('Estado', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gravedad', models.CharField(max_length=45)),
                ('Nombre', models.CharField(max_length=45)),
                ('Estado', models.BooleanField(null=True)),
                ('Consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Consulta')),
                ('Detalle_Enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Detalle_Enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Identificacion', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Direccion', models.CharField(max_length=45)),
                ('Genero', models.CharField(max_length=45)),
                ('Estado', models.BooleanField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Identificacion', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Direccion', models.CharField(max_length=45)),
                ('Genero', models.CharField(max_length=45)),
                ('Estado', models.BooleanField(null=True)),
                ('Foto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.DateTimeField()),
                ('Descripcion', models.CharField(max_length=200)),
                ('Estado', models.BooleanField(null=True)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Paciente')),
                ('Profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='Tipo_Profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Tipo_Profesional'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Usuario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='Cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Registrar_Cita'),
        ),
    ]
