# Generated by Django 2.1 on 2019-09-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20190911_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Genero', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='Foto',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Foto',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='Genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Genero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Genero'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='Foto',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='Genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Genero'),
        ),
    ]
