# Generated by Django 2.1 on 2019-09-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20190912_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
    ]
