# Generated by Django 2.1 on 2019-09-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20190912_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='Foto',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Foto',
        ),
    ]
