# Generated by Django 2.1 on 2019-09-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20190916_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='Email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_enfermedad',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrar_cita',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrar_cita',
            name='Hora',
            field=models.TimeField(),
        ),
    ]
