# Generated by Django 2.1 on 2019-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20190918_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='Foto',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Foto',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
    ]
